theme: jekyll-theme-minimal
google_analytics: UA-172953179-1

# Site Settings
title                    : "Ding He's lab"
title_separator          : "-"
name                     : &name "Ding He"
description: Welcome to our website. We study biogeochemistry in lakes and oceans.
url                      : https://hkustdinghe.github.io
